### ISSUE TITLE
Working with VSCoq

### ISSUE THREAD

**Issue by DKXXXL** [WasmCert/WasmCert-Coq#20]
Hi, I followed the installation guide but currently can only make this work using esy + Proof General.

I see in the README it also provides a way to work with VSCode.  I tried,`esy vscode` it says "Nothing to be done for `vscode`". 
I wonder  have you guys tried to use VSCode+VSCoq to develop this project here? I cannot seem to manage to port the esy environment to VsCoq.

EDIT : I forgot to say I am using VsCode remote here. `esy code` seems working fine (i.e. esy to start the vscode at the local machine)

Thanks for the help!

**Comment by DKXXXL** [comment]
Thanks for the information! The problem is resolved. For people who bumped into the similar problem I need to give some suggestions

1. esy is not working well with opam. When I have opam switch with different coq version, `esy emacs` (i.e. proof general)  will break. So I suggest just use a switch with no Coq install. (or if you don't have opam on your own, it is totally okay).
2. `esy vscode` will not work if under the current workspace `.vscode/settings.json` is already there. I think people familiar with esy can amend the script 
3. `esy vscode` is not generating precise information here.  It needs some manual fix:
3.a It is not generating correct JSON. Please make sure to fix it to correct JSON format
3.b The `-R` arguments are not precise. For me, it is mapping `.../mathcomp..../user-contrib` to `mathcomp`. Instead it should map `.../mathcomp..../user-contrib/mathcomp` to `mathcomp`. 
3.c also it forgets to map `.../theories` to `Wasm`. 

I think above hints can help to fix the whole issue here. Also thanks the author for the information!

**Comment by Mbodin** [comment]
I don't personally use VSCode so it's difficult for me to test if it's better. I pushed something that I think should solve 2, 3b, and 3c. Can you confirm that I did it right?

For 3a, I'm sorry but I'm surprised: did I forgot a quote somewhere?

About 1, I'm also surprised. Do you have something in your `.emacs.el` or `.emacs.d/init.el` that explicitly refers to an Opam folder?

**Comment by DKXXXL** [comment]
For 3a, I have something here still not working. In my terminal it says:
```
echo {"coqtop.binPath":"/home/e5jin/.esy/3/b/opam__s__coq-opam__c__8.13.2-b51095d2/bin","coqtop.args":["-coqlib","/home/e5jin/.esy/3/b/opam__s__coq-opam__c__8.13.2-b51095d2","-R","/home/e5jin/.esy/3___________________________________________________________________/i/coq_ext_lib-e8e19aad/user-contrib/ExtLib","ExtLib","-R","/home/e5jin/.esy/3___________________________________________________________________/i/coq_flocq-933af533/coq","Flocq","-R","/home/e5jin/.esy/3___________________________________________________________________/i/coq_itree-99ee9b31/user-contrib/ITree","ITree","-R","/home/e5jin/.esy/3___________________________________________________________________/i/coq_paco-5f8554ff/user-contrib/Paco","Paco","-R","/home/e5jin/.esy/3___________________________________________________________________/i/strong_induction-76dc6a29/lib/coq/user-contrib/StrongInduction","StrongInduction","-R","/home/e5jin/.esy/3___________________________________________________________________/i/compcert-e606ba59/coq","compcert","-R","/home/e5jin/.esy/3___________________________________________________________________/i/coq_mathcomp_ssreflect-678642f2/user-contrib/mathcomp","mathcomp","-R","/home/e5jin/.esy/3___________________________________________________________________/i/parseque-d8bdd937/lib/coq/user-contrib/parseque","parseque","-R","/home/e5jin/project/WasmCert-Coq/_build/default/theories","Wasm"]} > .vscode/settings.json
```
but when I check the settings.json. There is still not any quote there.  
<img width="344" alt="image" src="https://github.com/WasmCert/WasmCert-Coq/assets/16682424/6c0ebde1-2fee-4a4d-9e70-719f88596091">
I am not sure if it is platform relevant or some escape character is needed.

3b/3c seems solved.

Also when I say 2, I don't know what is the current behaviour but I have to warn you that override "settings.json" is not a good idea because the user might have some local setup in the "setting.json". 

It seems to me to just echo on the terminal and request the user to copy and paste the two settings for coqtop.binPath, and coqtop.args by themselves.  (Doing so you don't even have to fix the quote issue).

**Comment by Mbodin** [comment]
Thanks for the feedback! I think that I now understand the issue about the malformed JSON file. I will do another try.

**Comment by raoxiaojia** [comment]
Thanks a lot for helping with this Martin!
I'm looking to implement alternative compilation methods of the project (namely, via opam) instead of having to rely on esy in the near future (there was a previous issue on this) -- this might help users with existing Coq builds or wanting to integrate our project with others.
